### ISSUE TITLE
feature request: skip to last tick

### ISSUE THREAD

**Issue by msftsecurityteam** [thomasdullien/heap_history_viewer#1]
I am running this with a large application and it takes a good 10-15 seconds before I observe a crash while the hook is recording many allocations and frees, so it would be really awesome to skip to the last tick to inspect the state of everything at the end. This would make it much easier than having to keep clicking and dragging to the right.

**Comment by thomasdullien** [comment]
Hey there,

sorry for the long delay, I did not see this issue until now. Will have a look in the next month :-)

**Comment by msftsecurityteam** [comment]
I am going to close this out and make a note for anyone who stumbles on this: just place an event at the end of your JSON so you can see where the end of execution occurs :)
