### ISSUE TITLE
what():  parse error - unexpected end of input

### ISSUE THREAD

**Issue by probonopd** [thomasdullien/heap_history_viewer#3]
On Xubuntu 16.04 I am getting:

```
me@host:~$ Downloads/Heap_History_Viewer-x86_64.AppImage 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected end of input
Aborted
```

**Comment by thomasdullien** [comment]
Hey there,

error handling for command line arguments is particularly bad at the moment.

Try downloading heap.json and then doing
./Heap_History_Viewer-x86_64.AppImage /tmp/heap.json

Cheers,
Thomas

2018-04-17 21:22 GMT+02:00 probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
> Try downloading heap.json 

How would I do that? It would be great if the application could show a dialog telling the user what to do. Because right now most will be lost ;-)

**Comment by thomasdullien** [comment]
yeah i need to add *everything* related to "make the tool easy to use" --
sorry for that.

heap.json is part of the repository.

The GUI ingests a json heap description & draws rectangles from it.

I am on vacation this week, but in 1-2 weeks I will add more detailed docs
& tutorials.

Sorry for that!

probonopd <notifications@github.com> schrieb am Mi., 18. Apr. 2018, 01:36:

**Comment by thomasdullien** [comment]
Hey there,

update: The application now prompts with a file dialog to open a JSON.
